defaults:
  - algo: ppo
  - override hydra/launcher: submitit_local

seed: 0
device: 'cuda:1'
experiment: intersection

# WANDB things
wandb: True
wandb_name: nocturne
wandb_id: null
wandb_group: debug
debug: False

# TODO(eugenevinitsky) don't hardcode this
scenario_path: '/private/home/eugenevinitsky/Code/nocturne/scenarios/intersection.json'
view_angle: 1.56
dt: 1.0
rew_cfg:
  goal_tolerance: 5.0
  collision_penalty: -100.0
  shaped_goal_distance: True
  goal_achieved_bonus: 1.0
subscriber:
  include_ego_state: True
  # TODO(eugenevinitsky) this should be true
  include_visible_object_state: False
  object_subscriber:
    include_speed: True
    include_pos: True
  ego_subscriber:
    img_view: True
    view_angle: ${view_angle}
    include_speed: True
    include_heading: True
    include_pos: True
    include_goal_pos: True
    include_goal_img: True
    # include_lane_pos: True

hydra:
  run:
    dir: /checkpoint/eugenevinitsky/nocturne/test/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: /checkpoint/eugenevinitsky/nocturne/sweep/${now:%Y.%m.%d}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: /checkpoint/eugenevinitsky/nocturne/sweep/${now:%Y.%m.%d}/${now:%H%M}_${experiment}/.slurm
